CREATE TABLE CRICKETERS(
    NAME VARCHAR(30),
    AGE INT,
    TEAM VARCHAR(40),
    REGION VARCHAR(50),
    SALARY INT
)

INSERT  INTO CRICKETERS  VALUES('VIRAT KHOLI',35,'RCB','SOUTH',100000);

INSERT INTO CRICKETERS VALUES('PAT CUMMINS',40,'SRH','NORTH',70000);

INSERT INTO CRICKETERS VALUES('SHRAYAS AYYAR',30,'GT','EAST',80000);

INSERT INTO CRICKETERS VALUES('MAHENDRA SINGH DHONI',50,'CSK','SOUTH',50000);

INSERT INTO CRICKETERS VALUES('NOOR AHMED',25,'CSK','SOUTH',60000);

SELECT * FROM CRICKETERS ;

SELECT COUNT (*) FROM CRICKETERS ;

SELECT COUNT (*) FROM CRICKETERS 
WHERE TEAM = 'CSK' ;

SELECT SUM(SALARY) FROM CRICKETERS ;

SELECT AVG(SALARY) FROM CRICKETERS ;

SELECT MIN(SALARY) FROM CRICKETERS ;

SELECT MAX(SALARY) FROM CRICKETERS ;

SELECT * FROM CRICKETERS
WHERE TEAM = 'RCB';

SELECT * FROM CRICKETERS
ORDER BY (salary) DESC ;

SELECT TEAM,SUM(salary) AS top_cricketer
FROM CRICKETERS 
GROUP BY TEAM ;

SELECT TEAM,SUM(salary) AS top_cricketer
FROM CRICKETERS
GROUP BY TEAM
HAVING SUM(salary) <= 100000 ;



